"""Initial tables

Revision ID: 95e18e1d082e
Revises:
Create Date: 2024-11-04 22:31:53.034991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95e18e1d082e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bet",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "FINISHED_WIN", "FINISHED_LOSE", name="betstate"),
            nullable=False,
        ),
        sa.Column("summary", sa.Numeric(scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bet")
    # ### end Alembic commands ###
